webapp/routes.py
from flask import Blueprint, jsonify, request, render_template, current_app, url_for, redirect
from datetime import datetime
from .extensions import db  
from .models import User, WaterQualityData, Location
from .schemas import LocationSchema, UserSchema, UploadedDataSchema, VisualisationDataSchema, WaterQualityDataSchema,WaterQualityUpdateDataSchema
from marshmallow import ValidationError
from .model.model import predict_water_qaulity, load_the_model
from .utils import csv_to_dict
import os
from flask_login import current_user,login_required,login_user,logout_user
import pandas as pd


api_bp = Blueprint('api_bp', __name__)

# Create schema instances
location_schema = LocationSchema()
user_schema = UserSchema()
uploaded_data_schema = UploadedDataSchema()
visualisation_data_schema = VisualisationDataSchema()
water_quality_data_schema = WaterQualityDataSchema()

# Create Model instance
model = load_the_model()

def load_location_data_from_excel():
    basedir = os.path.abspath(os.path.dirname(__file__))
    excel_file_name = 'water_quality_locations.xlsx'
    excel_file_path = os.path.join(basedir, excel_file_name)
    df =pd.read_excel(excel_file_path,usecols=['Site number','Site Name','Decimal latitude', 'Decimal longitude'], sheet_name='locations')
    df.columns = ['site_number','location_name', 'latitude', 'longitude']

    # Insert data into database
    records = df.to_dict(orient='records')
    
    return records

def get_location_details(site_number, locations):
    for location in locations:
        print(type(location['site_number']))
        if location['site_number'] == int(site_number):
            return {
                'latitude': location['latitude'],
                'longitude': location['longitude'],
                'location_name': location['location_name']
            }
    # If site number not found, return None or handle accordingly
    return None


location_records = load_location_data_from_excel()

@api_bp.route('/')
def home():
    # Return the homepage
    # data = csv_to_dict()
    root_dir = os.path.dirname(current_app.root_path)
    data_dir = os.path.join(root_dir, 'original_data','dataset_mod.csv')
    data = csv_to_dict(data_dir)
    return render_template('index.html')


@api_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        data = request.get_json()
        username = data.get('username')
        password = data.get('password')
        # print(username, password)

        user = User.query.filter_by(username=username).first()

        if user and user.check_password(password):
            login_user(user)
            response = jsonify(message = "Login successful!", redirectURL=url_for('api_bp.dashboard'))
            return response
        else:
            return jsonify(message="Invalid credentials"), 401

    return render_template('registration/login.html')

@api_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        try:
            data = request.get_json()
            
            username = data.get('username')
            email = data.get('email')
            password = data.get('password')

            # Perform user creation logic (e.g., validation, password hashing, saving to database)
            new_user = User(username=username, email=email)
            new_user.set_password(password)
            db.session.add(new_user)
            db.session.commit()
            # flash('Signup successful!', 'signup_success')
            return jsonify(message="Signup successful!"), 201

        except Exception as e:
            # Handle any errors during user creation (e.g., database errors, validation failures)
            print(f"Error during signup: {e}")
            return jsonify(message="Signup failed", data={username,email,password}), 400

    # Render signup template on GET request
    return render_template('registration/signup.html')


@api_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('api_bp.login'))

@api_bp.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    # Get All the locations
    locations = Location.query.all()
    # Return the user-specific dashboard page content
    return render_template('dashboard/pages/index.html', locations=locations)

@api_bp.route('/upload', methods=['POST'])
@login_required
def upload_data():
    # Receive data and return the prediction
    data = request.json.get('data', None)
    # Data will be processed and a prediction will be made
    prediction_result = {"prediction": 0.75}  # Example output
    return jsonify(prediction_result), 201


@api_bp.route('/profile', methods=['GET', 'PATCH','POST'])
@login_required
def user_profile():

    if request.method == 'GET':
        return render_template('dashboard/pages/profile.html',user=current_user)

    elif request.method == 'PATCH':
        data = request.get_json()
        user = current_user
        
        if 'email' in data:
            user.email = data.get('email')
        if 'password' in data:
            user.set_password(data.get('password'))

        db.session.commit()
        return jsonify(message="Profile updated successfully"), 200

    return jsonify({"message": "User profile page"}), 200


@api_bp.route('/account', methods=['DELETE'])
@login_required
def delete_account():
    user = User.query.filter_by(username=current_user.username).first()
    if not user:
        return jsonify(message="User not found"), 404
    logout_user()
    # Uncommend after testing
    db.session.delete(user)
    db.session.commit()
    response = jsonify(message="success full",success_url=url_for('api_bp.home') )
    return response


@api_bp.route('/history', methods=['GET'])
@login_required
def get_history():
    # Logic to retrieve the history of user uploads and predictions
    return render_template('dashboard/pages/history.html')

# @api_bp.route('/visualization_data', methods=["GET"])
# def visualization_data():
#     root_dir = os.path.dirname(current_app.root_path)
#     data_dir = os.path.join(root_dir, 'original_data','dataset_mod.csv')
#     data = csv_to_dict(data_dir)
#     def format_floats(data):
#         """Formats floats in a dictionary to have two decimal places."""
#         for item in data:    
#             for key, value in item.items():
#                 if isinstance(value, float):
#                     item[key] = float("%.15f" % value)
#         return data
    
#     formatted_data = format_floats(data.copy())
#     print(formatted_data)
#     return jsonify(formatted_data), 200 
 
@api_bp.route('/visualization_data', methods=["POST"])
def visualization_data():
    
    data = request.json

    # Extract form fields

    site_number = data.get('site-number')
    location_data = get_location_details(site_number=site_number,locations=location_records)
    
    
    print(site_number)
    print(location_data)
    
    root_dir = os.path.dirname(current_app.root_path)
    data_dir = os.path.join(root_dir, 'data',f'{site_number}.csv')
    
    df =pd.read_csv(data_dir)
    
    # Define the mapping of old column names to new column names
    column_mapping = {
        'Unnamed: 0': 'Unnamed: 0',
        'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Maximum)': 'spec_cond_max',
        'pH, water, unfiltered, field, standard units (Maximum)': 'ph_max',
        'pH, water, unfiltered, field, standard units (Minimum)': 'ph_min',
        'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Minimum)': 'spec_cond_min',
        'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Mean)': 'spec_cond_mean',
        'Dissolved oxygen, water, unfiltered, milligrams per liter (Maximum)': 'dissolved_oxy_max',
        'Dissolved oxygen, water, unfiltered, milligrams per liter (Mean)': 'dissolved_oxy_mean',
        'Dissolved oxygen, water, unfiltered, milligrams per liter (Minimum)': 'dissolved_oxy_min',
        'Temperature, water, degrees Celsius (Mean)': 'temp_mean',
        'Temperature, water, degrees Celsius (Minimum)': 'temp_min',
        'Temperature, water, degrees Celsius (Maximum)': 'temp_max',
        'Water Quality': 'water_quality',
        'Training': 'training',
        'Location ID': 'location_id',
        'Date': 'date'
    }

    # Rename the columns using the mapping
    df = df.rename(columns=column_mapping)
        
    data = df.to_dict(orient='records')
    
    def format_floats(data):
        """Formats floats in a dictionary to have two decimal places."""
        for item in data:    
            for key, value in item.items():
                if isinstance(value, float):
                    item[key] = float("%.15f" % value)
        return data
    
    formatted_data = format_floats(data.copy())
    # print(formatted_data)
    return jsonify({'plotData':formatted_data,'location':location_data}), 200  
    
@api_bp.route('/water_quality_data', methods=["GET"])
def water_quality_data():
    water_quality_data = db.session.query(WaterQualityData, Location.location_name).join(Location, WaterQualityData.location_id == Location.location_id).all()
    data = [
        {
            'Location ID': row.location_id,
            'Location Name': location,  # Access location name from joined data
            'Date': row.date.strftime('%a, %b %d, %Y'),
            'Spec_Cond_Max': row.spec_cond_max,
            'PH_Max':row.ph_max,
            'PH_Min':row.ph_min,
            'Spec_Cond_Min':row.spec_cond_min,
            'Spec_Cond_Mean':row.spec_cond_mean,
            'Dissolved_Oxy_Max':row.dissolved_oxy_max,
            'Dissolved_Oxy_Mean':row.dissolved_oxy_mean,
            'Dissolved_Oxy_Min':row.dissolved_oxy_min,
            'Temp Mean':row.temp_mean,
            'Temp Min':row.temp_min,
            'Temp Max':row.temp_max,

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <!DOCTYPE html>
    <html lang="en">
    
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">
    
        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">
    
        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
        
        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    
        <!-- Libraries Stylesheet -->
        <link href="{{url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
        <link href="{{url_for('static', filename='lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css')}}" rel="stylesheet" />
    
        <!-- Customized Bootstrap Stylesheet -->
        <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">

        <!-- Datatable css -->
        <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.bootstrap5.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.1/css/responsive.bootstrap5.css">

        <!-- Plotly library -->
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    
        <!-- Template Stylesheet -->
        <link href="{{url_for('static', filename='css/style.css')}}" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

        <title>{%block title%}{% endblock %}{% if appinfo %}{{appinfo.name}}{% endif %}</title>
    </head>
<body>
    <!-- Content End-->
    {% block content %}
    {% endblock%}
    {% include "svgs.html" %}
    <!--
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    -->
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{{url_for('static', filename='lib/chart/chart.min.js')}}"></script>
        <script src="{{url_for('static', filename='lib/easing/easing.min.js')}}"></script>
        <script src="{{url_for('static', filename='lib/waypoints/waypoints.min.js')}}"></script>
        <script src="{{url_for('static', filename='lib/owlcarousel/owl.carousel.min.js')}}"></script>
        <script src="{{url_for('static', filename='lib/tempusdominus/js/moment.min.js')}}"></script>
        <script src="{{url_for('static', filename='lib/tempusdominus/js/moment-timezone.min.js')}}"></script>
        <script src="{{url_for('static', filename='lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js')}}"></script>

        <!-- DataTable file -->
        <script src="//cdn.datatables.net/2.0.3/js/dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/2.0.3/js/dataTables.bootstrap5.js"></script>
        <script src="https://cdn.datatables.net/responsive/3.0.1/js/dataTables.responsive.js"></script>
        <script src="https://cdn.datatables.net/responsive/3.0.1/js/responsive.bootstrap5.js"></script>
        <!-- Template Javascript -->
        <script src="{{url_for('static', filename='js/main.js')}}"></script>
        <script src="{{url_for('static', filename='js/index.js')}}"></script>

        
</body>
</html>

webapp/templates/index.html
{% extends 'base.html'%}
{% block title%}Home | {% endblock%}
{% block content %}
<!-- Navbar Start -->
<nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
    <a href="{{ url_for('api_bp.home' ) }}" class="sidebar-toggler flex-shrink-0">
        <!-- <i class="fa fa-home"></i> -->
        <h2 class="text-primary">
            {% if appinfo %}{{appinfo.name}}{% endif %}
        </h2>
    </a>
    <div class="navbar-nav align-items-center ms-auto">
        <a href="{{ url_for('api_bp.login' ) }}" class=" btn btn-outline-secondary rounded-pill m-2">Login</a>
        <a href="{{ url_for('api_bp.signup' ) }}" class="btn btn-primary rounded-pill m-2">Signup</a>
</nav>
<!-- Navbar End -->


{% endblock %}

webapp/templates/svgs.html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </symbol>
    <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
  </svg>