webapp/routes.py
from flask import Blueprint, jsonify, request, render_template, current_app, url_for, redirect
from datetime import datetime
from .extensions import db  
from .models import User, WaterQualityData, Location
from .schemas import LocationSchema, UserSchema, UploadedDataSchema, VisualisationDataSchema, WaterQualityDataSchema,WaterQualityUpdateDataSchema
from marshmallow import ValidationError
from .model.model import predict_water_qaulity, load_the_model
from .utils import csv_to_dict
import os
from flask_login import current_user,login_required,login_user,logout_user
import pandas as pd


api_bp = Blueprint('api_bp', __name__)

# Create schema instances
location_schema = LocationSchema()
user_schema = UserSchema()
uploaded_data_schema = UploadedDataSchema()
visualisation_data_schema = VisualisationDataSchema()
water_quality_data_schema = WaterQualityDataSchema()

# Create Model instance
model = load_the_model()

def load_location_data_from_excel():
    basedir = os.path.abspath(os.path.dirname(__file__))
    excel_file_name = 'water_quality_locations.xlsx'
    excel_file_path = os.path.join(basedir, excel_file_name)
    df =pd.read_excel(excel_file_path,usecols=['Site number','Site Name','Decimal latitude', 'Decimal longitude'], sheet_name='locations')
    df.columns = ['site_number','location_name', 'latitude', 'longitude']

    # Insert data into database
    records = df.to_dict(orient='records')
    
    return records

def get_location_details(site_number, locations):
    for location in locations:
        print(type(location['site_number']))
        if location['site_number'] == int(site_number):
            return {
                'latitude': location['latitude'],
                'longitude': location['longitude'],
                'location_name': location['location_name']
            }
    # If site number not found, return None or handle accordingly
    return None


location_records = load_location_data_from_excel()

@api_bp.route('/')
def home():
    # Return the homepage
    # data = csv_to_dict()
    root_dir = os.path.dirname(current_app.root_path)
    data_dir = os.path.join(root_dir, 'original_data','dataset_mod.csv')
    data = csv_to_dict(data_dir)
    return render_template('index.html')


@api_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        data = request.get_json()
        username = data.get('username')
        password = data.get('password')
        # print(username, password)

        user = User.query.filter_by(username=username).first()

        if user and user.check_password(password):
            login_user(user)
            response = jsonify(message = "Login successful!", redirectURL=url_for('api_bp.dashboard'))
            return response
        else:
            return jsonify(message="Invalid credentials"), 401

    return render_template('registration/login.html')

@api_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        try:
            data = request.get_json()
            
            username = data.get('username')
            email = data.get('email')
            password = data.get('password')

            # Perform user creation logic (e.g., validation, password hashing, saving to database)
            new_user = User(username=username, email=email)
            new_user.set_password(password)
            db.session.add(new_user)
            db.session.commit()
            # flash('Signup successful!', 'signup_success')
            return jsonify(message="Signup successful!"), 201

        except Exception as e:
            # Handle any errors during user creation (e.g., database errors, validation failures)
            print(f"Error during signup: {e}")
            return jsonify(message="Signup failed", data={username,email,password}), 400

    # Render signup template on GET request
    return render_template('registration/signup.html')


@api_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('api_bp.login'))

@api_bp.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    # Get All the locations
    locations = Location.query.all()
    # Return the user-specific dashboard page content
    return render_template('dashboard/pages/index.html', locations=locations)

@api_bp.route('/upload', methods=['POST'])
@login_required
def upload_data():
    # Receive data and return the prediction
    data = request.json.get('data', None)
    # Data will be processed and a prediction will be made
    prediction_result = {"prediction": 0.75}  # Example output
    return jsonify(prediction_result), 201


@api_bp.route('/profile', methods=['GET', 'PATCH','POST'])
@login_required
def user_profile():

    if request.method == 'GET':
        return render_template('dashboard/pages/profile.html',user=current_user)

    elif request.method == 'PATCH':
        data = request.get_json()
        user = current_user
        
        if 'email' in data:
            user.email = data.get('email')
        if 'password' in data:
            user.set_password(data.get('password'))

        db.session.commit()
        return jsonify(message="Profile updated successfully"), 200

    return jsonify({"message": "User profile page"}), 200


@api_bp.route('/account', methods=['DELETE'])
@login_required
def delete_account():
    user = User.query.filter_by(username=current_user.username).first()
    if not user:
        return jsonify(message="User not found"), 404
    logout_user()
    # Uncommend after testing
    db.session.delete(user)
    db.session.commit()
    response = jsonify(message="success full",success_url=url_for('api_bp.home') )
    return response


@api_bp.route('/history', methods=['GET'])
@login_required
def get_history():
    # Logic to retrieve the history of user uploads and predictions
    return render_template('dashboard/pages/history.html')

# @api_bp.route('/visualization_data', methods=["GET"])
# def visualization_data():
#     root_dir = os.path.dirname(current_app.root_path)
#     data_dir = os.path.join(root_dir, 'original_data','dataset_mod.csv')
#     data = csv_to_dict(data_dir)
#     def format_floats(data):
#         """Formats floats in a dictionary to have two decimal places."""
#         for item in data:    
#             for key, value in item.items():
#                 if isinstance(value, float):
#                     item[key] = float("%.15f" % value)
#         return data
    
#     formatted_data = format_floats(data.copy())
#     print(formatted_data)
#     return jsonify(formatted_data), 200 
 
@api_bp.route('/visualization_data', methods=["POST"])
def visualization_data():
    
    data = request.json

    # Extract form fields

    site_number = data.get('site-number')
    location_data = get_location_details(site_number=site_number,locations=location_records)
    
    
    print(site_number)
    print(location_data)
    
    root_dir = os.path.dirname(current_app.root_path)
    data_dir = os.path.join(root_dir, 'data',f'{site_number}.csv')
    
    df =pd.read_csv(data_dir)
    
    # Define the mapping of old column names to new column names
    column_mapping = {
        'Unnamed: 0': 'Unnamed: 0',
        'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Maximum)': 'spec_cond_max',
        'pH, water, unfiltered, field, standard units (Maximum)': 'ph_max',
        'pH, water, unfiltered, field, standard units (Minimum)': 'ph_min',
        'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Minimum)': 'spec_cond_min',
        'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Mean)': 'spec_cond_mean',
        'Dissolved oxygen, water, unfiltered, milligrams per liter (Maximum)': 'dissolved_oxy_max',
        'Dissolved oxygen, water, unfiltered, milligrams per liter (Mean)': 'dissolved_oxy_mean',
        'Dissolved oxygen, water, unfiltered, milligrams per liter (Minimum)': 'dissolved_oxy_min',
        'Temperature, water, degrees Celsius (Mean)': 'temp_mean',
        'Temperature, water, degrees Celsius (Minimum)': 'temp_min',
        'Temperature, water, degrees Celsius (Maximum)': 'temp_max',
        'Water Quality': 'water_quality',
        'Training': 'training',
        'Location ID': 'location_id',
        'Date': 'date'
    }

    # Rename the columns using the mapping
    df = df.rename(columns=column_mapping)
        
    data = df.to_dict(orient='records')
    
    def format_floats(data):
        """Formats floats in a dictionary to have two decimal places."""
        for item in data:    
            for key, value in item.items():
                if isinstance(value, float):
                    item[key] = float("%.15f" % value)
        return data
    
    formatted_data = format_floats(data.copy())
    # print(formatted_data)
    return jsonify({'plotData':formatted_data,'location':location_data}), 200  
    
@api_bp.route('/water_quality_data', methods=["GET"])
def water_quality_data():
    water_quality_data = db.session.query(WaterQualityData, Location.location_name).join(Location, WaterQualityData.location_id == Location.location_id).all()
    data = [
        {
            'Location ID': row.location_id,
            'Location Name': location,  # Access location name from joined data
            'Date': row.date.strftime('%a, %b %d, %Y'),
            'Spec_Cond_Max': row.spec_cond_max,
            'PH_Max':row.ph_max,
            'PH_Min':row.ph_min,
            'Spec_Cond_Min':row.spec_cond_min,
            'Spec_Cond_Mean':row.spec_cond_mean,
            'Dissolved_Oxy_Max':row.dissolved_oxy_max,
            'Dissolved_Oxy_Mean':row.dissolved_oxy_mean,
            'Dissolved_Oxy_Min':row.dissolved_oxy_min,
            'Temp Mean':row.temp_mean,
            'Temp Min':row.temp_min,
            'Temp Max':row.temp_max,

webapp/templates/dashboard/base.html
{% extends "base.html" %}
{% block content %}
    <!-- Dashboard -->
    <div class="container-xxl position-relative bg-white d-flex p-0">
        {% include "dashboard/sidebar.html" %}
        <!-- Content Start -->
        <div class="content">
            {% include 'dashboard/navbar.html' %}
                <div class="container-fluid pt-4 px-4 g-4">
                    {% block dashboard %}
                    {% endblock %} 
                </div>
            {% include "dashboard/footer.html" %}
        </div>
    </div>
    <!-- Navbar -->

<script>
</script>

{% endblock content %}

webapp/templates/dashboard/footer.html
<!-- Footer Start -->
<div class="container-fluid pt-4 px-4">
    <div class="bg-light rounded-top p-4">
        <div class="row">
            <div class="col-12 col-sm-6 text-center text-sm-start">
                &copy; <a href="{{ url_for('api_bp.dashboard' ) }}">{% if appinfo %}{{appinfo.name}}{% endif %}</a>, All Right Reserved. 
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

webapp/templates/dashboard/navbar.html
<!-- Navbar Start -->
<nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
    <a href="{{ url_for('api_bp.dashboard' ) }}" class="navbar-brand d-flex d-lg-none me-4">
        <h2 class="text-primary mb-0"><i class="fa fa-home"></i></h2>
    </a>
    <a href="#" class="sidebar-toggler flex-shrink-0">
        <i class="fa fa-bars"></i>
    </a>
    <!-- <form class="d-none d-md-flex ms-4">
        <input class="form-control border-0" type="search" placeholder="Search">
    </form> -->
    <div class="navbar-nav align-items-center ms-auto">
        <!--  
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-envelope me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Message</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all message</a>
            </div>
        </div>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-bell me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Notificatin</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">Profile updated</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">New user added</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">Password changed</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all notifications</a>
            </div>
        </div>
        -->
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <!-- <img class="rounded-circle me-lg-2" src="img/user.jpg" alt="" style="width: 40px; height: 40px;"> -->
                <div class="rounded-circle d-inline-block justify-content-center align-items-center text-center bg-primary text-white fw-bolder fs-3 me-lg-2" style="width: 40px; height: 40px;">
                    <b>{{ current_user.username[:1] }}</b>
                  </div>

                <span class="d-none d-lg-inline-flex">
                    {% if current_user %}
                        {{current_user.username}}
                    {% endif %}
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                <a href="{{url_for('api_bp.user_profile')}}" class="dropdown-item">My Profile</a>
                <!-- <a href="#" class="dropdown-item">Settings</a> -->
                <a href="{{ url_for('api_bp.logout' ) }}" class="dropdown-item">Log Out</a>
            </div>
        </div>
        
    </div>
</nav>
<!-- Navbar End -->

webapp/templates/dashboard/sidebar.html
<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-light navbar-light">
        <a href="{{ url_for('api_bp.dashboard' ) }}" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary">{% if appinfo %}{{appinfo.name}}{% endif %}</h3>
        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <div class="rounded-circle d-flex justify-content-center align-items-center text-center bg-primary fw-bolder fs-3 text-dark" alt="" style="width: 40px; height: 40px" >
                    <b >{% if current_user %}
                        {{current_user.username[:1]}}
                    {% endif %}
                </b>
                </div>
                <div
                    class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
                </div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">
                    {% if current_user %}
                        {{current_user.username}}
                    {% endif %}
                </h6>
                <!-- <span>Admin</span> -->
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{{ url_for('api_bp.dashboard' ) }}" class="nav-item nav-link {% if request.path == url_for('api_bp.dashboard') %}active{% endif %}"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
            <!-- <a href="{{ url_for('api_bp.get_history' ) }}" class="nav-item nav-link {% if request.path == url_for('api_bp.get_history') %}active{% endif %}"><i class="fa fa-history me-2"></i>History</a> -->
            <a href="{{ url_for('api_bp.get_predictions' ) }}" class="nav-item nav-link {% if request.path == url_for('api_bp.get_predictions') %}active{% endif %}"><i class="fa fa-chart-area me-2"></i>Predictions</a>
            <a href="{{ url_for('api_bp.get_insights' ) }}" class="nav-item nav-link {% if request.path == url_for('api_bp.get_insights') %}active{% endif %}"><i class="fa fa-chart-pie me-2"></i>Insights</a>
            <a href="{{ url_for('api_bp.user_profile' ) }}" class="nav-item nav-link {% if request.path == url_for('api_bp.user_profile') %}active{% endif %}"><i class="fa fa-user-circle me-2"></i>Profile</a>


        </div>
    </nav>
</div>
<!-- Sidebar End -->